name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

  validate-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: gradle/actions/wrapper-validation@94baf225fe0a508e581a564467443d0e2379123b # v4

  ktlint:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: ktlint
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: ktlintFormat
          check-task: ktlintCheck

  spotless:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: spotless
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: spotlessApply
          check-task: spotlessCheck

  dependency-guard:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: dependency-guard
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: dependencyGuardBaseline
          check-task: dependencyGuard

  curator:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: curator
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: curatorDump
          check-task: curatorCheck

  moduleCheck:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: moduleCheck
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: moduleCheckAuto
          check-task: moduleCheck

  doks:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: doks
        uses: rickbusarow/actions/gradle-task-with-commit@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: doks
          check-task: doksCheck

  check-version-is-snapshot:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: check version is snapshot
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: checkVersionIsSnapshot

  detekt:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: detektAll
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: detektAll
          restore-cache-key: main-build-artifacts

      - name: merge detekt SARIF reports
        if: success() || failure()
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: detektReportMerge

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merged.sarif

  unit-tests-ubuntu:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: all tests
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: test
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: failure()
        with:
          name: unit-test-results-ubuntu
          path: ./**/build/reports/tests/

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        if: failure()
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Unit test results
        uses: mikepenz/action-junit-report@b14027d33d3a745ccc4d6a12f649e83110b5a373 # v5
        if: failure()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  unit-tests-windows:
    runs-on: windows-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: all tests
        uses: rickbusarow/actions/gradle-task@c602f8da97f00279c6e77d3f25cbedcbf24ef936 # v1
        with:
          task: test
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: failure()
        with:
          name: unit-test-results-windows
          path: ./**/build/reports/tests/

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        if: failure()
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Unit test results
        uses: mikepenz/action-junit-report@b14027d33d3a745ccc4d6a12f649e83110b5a373 # v5
        if: failure()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - windows

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - check-version-is-snapshot
      - curator
      - dependency-guard
      - detekt
      - doks
      - ktlint
      - moduleCheck
      - spotless
      - unit-tests-ubuntu
      - unit-tests-windows
      - validate-wrapper

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
