name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

  validate-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: gradle/wrapper-validation-action@216d1ad2b3710bf005dc39237337b9673fd8fcd5 # v3

  ktlint:
    runs-on: macos-14
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: ktlint
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: ktlintFormat
          check-task: ktlintCheck

  spotless:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: spotless
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: spotlessApply
          check-task: spotlessCheck

  dependency-guard:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: dependency-guard
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: dependencyGuardBaseline
          check-task: dependencyGuard

  curator:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: curator
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: curatorDump
          check-task: curatorCheck

  moduleCheck:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: moduleCheck
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: moduleCheckAuto
          check-task: moduleCheck

  doks:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: doks
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: doks
          check-task: doksCheck

  check-version-is-snapshot:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: check version is snapshot
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: checkVersionIsSnapshot

  detekt:
    runs-on: macos-14
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: detektAll
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: detektAll
          restore-cache-key: main-build-artifacts

      - name: merge detekt SARIF reports
        if: success() || failure()
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: detektReportMerge

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merged.sarif

  unit-tests-ubuntu:
    runs-on: ubuntu-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: all tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: test
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if: failure()
        with:
          name: unit-test-results-ubuntu
          path: ./**/build/reports/tests/

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        if: failure()
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Unit test results
        uses: mikepenz/action-junit-report@ac30be7acb0a361e5492575ab42e47fcadec4928 # v4
        if: failure()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  unit-tests-windows:
    runs-on: windows-latest
    needs:
      - validate-wrapper
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: all tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: test
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if: failure()
        with:
          name: unit-test-results-windows
          path: ./**/build/reports/tests/

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        id: app-token
        if: failure()
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Unit test results
        uses: mikepenz/action-junit-report@ac30be7acb0a361e5492575ab42e47fcadec4928 # v4
        if: failure()
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - windows

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - check-version-is-snapshot
      - curator
      - dependency-guard
      - detekt
      - doks
      - ktlint
      - moduleCheck
      - spotless
      - unit-tests-ubuntu
      - unit-tests-windows
      - validate-wrapper

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
