name: Renovate

on:
  workflow_dispatch:
  issues:
    types:
      - edited
  pull_request:
    types:
      - edited
    branches:
      - github-renovate/*

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@ea850436a5fe75c0925d583c7a02c60a5865461d # v43.0.20
        with:
          configurationFile: .github/renovate-sh.json5
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: debug
