name: Renovate

on:
  schedule:
    # every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch:
  issues:
  label:
  pull_request:
    types:
      # run when the little "click here to rebase" box is checked.
      - synchronize
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@a1ed1d0adddfdf138192d1fbe3150a80094dee6a # v40.3.1
        with:
          configurationFile: .github/renovate-sh.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: debug
